export default {
  races: [
    {
      race_id: 1,
      race_course: "東京",
      round: "1R",
      race_name: "天皇賞(秋)",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 2,
      race_course: "東京",
      round: "2R",
      race_name: "3歳未勝利",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 3,
      race_course: "東京",
      round: "3R",
      race_name: "天皇賞(秋)",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 4,
      race_course: "東京",
      round: "4R",
      race_name: "3歳未勝利",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 5,
      race_course: "東京",
      round: "5R",
      race_name: "天皇賞(秋)",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 6,
      race_course: "東京",
      round: "6R",
      race_name: "3歳未勝利",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 7,
      race_course: "東京",
      round: "7R",
      race_name: "天皇賞(秋)",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 8,
      race_course: "東京",
      round: "8R",
      race_name: "3歳未勝利",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 9,
      race_course: "中京",
      round: "1R",
      race_name: "チャンピオンカップ",
      course_type: "ダート",
      length: 2200,
      population: 999999,
    },
    {
      race_id: 10,
      race_course: "中京",
      round: "2R",
      race_name: "新馬",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 11,
      race_course: "中京",
      round: "3R",
      race_name: "チャンピオンカップ",
      course_type: "ダート",
      length: 2200,
      population: 999999,
    },
    {
      race_id: 12,
      race_course: "中京",
      round: "4R",
      race_name: "新馬",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 13,
      race_course: "中京",
      round: "5R",
      race_name: "チャンピオンカップ",
      course_type: "ダート",
      length: 2200,
      population: 999999,
    },
    {
      race_id: 14,
      race_course: "中京",
      round: "6R",
      race_name: "新馬",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 15,
      race_course: "中京",
      round: "7R",
      race_name: "チャンピオンカップ",
      course_type: "ダート",
      length: 2200,
      population: 999999,
    },
    {
      race_id: 16,
      race_course: "中京",
      round: "8R",
      race_name: "新馬",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 17,
      race_course: "阪神",
      round: "1R",
      race_name: "宝塚記念",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 18,
      race_course: "阪神",
      round: "2R",
      race_name: "2勝クラス",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 19,
      race_course: "阪神",
      round: "3R",
      race_name: "宝塚記念",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 20,
      race_course: "阪神",
      round: "4R",
      race_name: "2勝クラス",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 21,
      race_course: "阪神",
      round: "5R",
      race_name: "宝塚記念",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 22,
      race_course: "阪神",
      round: "6R",
      race_name: "2勝クラス",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 23,
      race_course: "阪神",
      round: "7R",
      race_name: "宝塚記念",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_id: 24,
      race_course: "阪神",
      round: "8R",
      race_name: "2勝クラス",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
  ],
};
