export default {
  race: {
    race_id: 1,
    race_course: "東京",
    round: "11R",
    race_name: "天皇賞(秋)",
    course_type: "芝",
    length: 1600,
    population: 999999,
    horses: [
      {
        gate_number: 1,
        number: 1,
        name: "グランアレグリア",
        sex: "牝",
        age: 5,
        weight: 56,
        jockey: "C.ルメール",
        stable: "音無",
        horse_weight: 500,
        horse_weight_gain_or_loss: -10,
        odds: 1.5,
        popularity: 1,
      },
      {
        gate_number: 1,
        number: 2,
        name: "エフフォーリア",
        sex: "牡",
        age: 3,
        weight: 58,
        jockey: "横山（武）",
        stable: "国枝",
        horse_weight: 520,
        horse_weight_gain_or_loss: 10,
        odds: 2.6,
        popularity: 3,
      },
      {
        gate_number: 2,
        number: 3,
        name: "コントレイル",
        sex: "牡",
        age: 4,
        weight: 58,
        jockey: "福永",
        stable: "池添（学）",
        horse_weight: 510,
        horse_weight_gain_or_loss: 3,
        odds: 2.2,
        popularity: 2,
      },
    ],
  },
};
