export default {
  races: [
    {
      race_course: "東京",
      round: "11R",
      race_name: "天皇賞(秋)",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_course: "東京",
      round: "12R",
      race_name: "3歳未勝利",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_course: "中京",
      round: "11R",
      race_name: "チャンピオンカップ",
      course_type: "ダート",
      length: 2200,
      population: 999999,
    },
    {
      race_course: "中京",
      round: "12R",
      race_name: "新馬",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_course: "阪神",
      round: "11R",
      race_name: "宝塚記念",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
    {
      race_course: "阪神",
      round: "12R",
      race_name: "2勝クラス",
      course_type: "芝",
      length: 1600,
      population: 999999,
    },
  ],
};
